[project]
name = "vector-tapper-soda-shop-logic"
version = "0.1.0"
description = "Serve thirsty customers before they reach the end of the bar in this fast-paced retro management sim"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
]
